// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {enumerator} from '../models';

export function GetSerialPortList():Promise<Array<enumerator.PortDetails>>;

export function Greet(arg1:string):Promise<string>;

export function OpenInBrowser(arg1:string,arg2:Array<string>):Promise<void>;
